### ISSUE TITLE
HAL: CRYP: HAL_CRYP_SetConfig parameters not initialized

### ISSUE THREAD

**Issue by str4t0m** [STMicroelectronics/STM32CubeWL#17]
**Describe the set-up**
 * A project using the CRYP HAL driver from STM32CubeWL

**Describe the bug**
The functions: `HAL_CRYP_SetConfig` and `HAL_CRYP_GetConfig` don't initialize all parameters of the `CRYP_ConfigTypeDef` struct. `HeaderWidthUnit` and `KeyIVConfigSkip` are not initialized.

See:
https://github.com/STMicroelectronics/STM32CubeWL/blob/747d4e27df07dcfc995b54f8af8a0bee38dfef8d/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp.c#L589-L598
and:
https://github.com/STMicroelectronics/STM32CubeWL/blob/747d4e27df07dcfc995b54f8af8a0bee38dfef8d/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp.c#L656-L664

**How To Reproduce**
Encrypt or decrypt data using GCM or CCM Mode with a given HeaderWidthUnit different from `CRYP_HEADERWIDTHUNIT_WORD`.
This will lead to wrong Tag calculation in AEAD algorithms because the HAL multiplies the given header length by 4 and calculates the Additional Authenticated Data over a too big range.

**Comment by ASELSTM** [comment]
Hi @str4t0m,

This issue has been fixed within the latest release **v1.1.0** of [STM32CubeWL](https://github.com/STMicroelectronics/STM32CubeWL) which is already available on GitHub.

`HAL_CRYP_SetConfig()` :
https://github.com/STMicroelectronics/STM32CubeWL/blob/1555f88ae1c5898c239bd8a8520203a776ab4995/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp.c#L589-L600


`HAL_CRYP_GetConfig()` :
https://github.com/STMicroelectronics/STM32CubeWL/blob/1555f88ae1c5898c239bd8a8520203a776ab4995/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp.c#L657-L668

As the fix is already implemented please allow me to close this thread.  Thank you for your contribution.

With regards,
