### ISSUE TITLE
DeviceEUI missing in LoRaWAN Commisioning .ioc file

### ISSUE THREAD

**Issue by edchron** [STMicroelectronics/STM32CubeWL#59]
Hello, I want to report something missing in the .ioc file in v1.3.0.
In previous version, there is Device EUI settings in the Middleware/LORAWAN/LoRaWAN Commisioning.  But, in v1.3.0 there is no any Device EUI config. I thought it has changed to AppEUI one and I found that it wasn't. 

I'm hoping there will be a solution for this issue because I'd really love to use the newest version. Thanks!

![image](https://user-images.githubusercontent.com/63876304/209444911-f51f51b7-efae-4046-b1d6-961e7b0d6b5e.png)

**Comment by ASELSTM** [comment]
Hi  @edchron,

The point you reported is actually related to the ecosystem (namely the CubeMX tool) rather than the firmware published within this repository (CMSIS, HAL, BSP, etc.),  Unfortunately, we don't treat aspect related to CubeMX tool in our GitHub repositories. They are rather treated at the [STM32CubeMX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated page of the **ST Community** .   There you shall find people who will address your request and whom you will hopefully find a solution with.

Please allow me thus to close this thread. Thank you for your comprehension and thank you again for having reported.

With regards,
