### ISSUE TITLE
Missing include file

### ISSUE THREAD

**Issue by Strooom** [STMicroelectronics/STM32CubeWL#78]
When installing this repository, it's not possible to build an application because
`Utilities/misc/stm32_systime_if_template.c` is including `#include "stm32_systime_if.h"` but this file is not present in the repository.
If you copy `Utilities/misc/stm32_systime_if_template.h` to `Utilities/misc/stm32_systime_if.h`, the build succeeds, but there are afaik no instructions why this would be needed.

Please, either add the file `Utilities/misc/stm32_systime_if.h` or add instructions on how to create the file from `Utilities/misc/stm32_systime_if_template.h`

**Comment by RJMSTM** [comment]
Hello @Strooom,

Thank you for your report. According to our development team, the stm32_systime_if_template.c file is a user file, while the stm32_systime_if_template.c file is a customizable file for each application. In order to emphasize each use case, a generic file is proposed as a reference template.

Please allow me to close this issue now. Thank you once again for your report. We are looking forward to reading from you again.

With Regards
